name = "Baldfabi"
license = "MIT"
licenselink = "https://github.com/BaldFabi/blog/blob/master/themes/baldfabi/LICENSE"
description = ""
homepage = "https://baldfabi.dev/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "BaldFabi"
  homepage = "https://baldfabi.dev"
