baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'BaldFabi Blog'
theme = 'baldfabi'

[taxanomies]
    tag = "tags"
    category = "categories"

[markup.highlight]
    linenos = true
    anchorLineNos = true
    lineanchors = "L"
    style = "dracula"

[module]
    [[module.mounts]]
        source = "./node_modules/@fontsource/saira/files"
        target = "static/css/files"
    [[module.mounts]]
        source = "./node_modules/@fortawesome/fontawesome-free/webfonts"
        target = "static/webfonts"